# Generated by Django 2.2.16 on 2023-01-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
