# Generated by Django 2.2.16 on 2023-01-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='follow',
        ),
    ]
